### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by batisteo** [console-rs/dialoguer#11]
It would be nice to have something similar:

![](https://raw.githubusercontent.com/citguru/PyInquirer/master/docs/images/input-prompt.png)

https://github.com/CITGuru/PyInquirer/#input---type-input

**Comment by nicohman** [comment]
I added some basic input validation functionality, including prebuilt phone number and email address validators. Are there any other validators that you think should be in by default?

**Comment by jamesmcm** [comment]
Would it be possible to disallow the user to even enter characters for example?

So like we could set an Input to be numeric only, and pressing non-digits has no effect?

I haven't checked the source code to see if you handle it as a line of input or character by character, so this might not be possible.

**Comment by pksunkara** [comment]
No, that needs changes in the interaction logic for prompts. You can either write one yourself or if it's something common like a number, then contribute it to the library.

**Comment by RobWalt** [comment]
@batisteo I don't know when it was added, but there exists an [input validation feature](https://docs.rs/dialoguer/latest/dialoguer/struct.Input.html#method.validate_with) now. If you have some spare time, can you check if this is what you originally envisioned when you opened the issue?

**Comment by batisteo** [comment]
I guess it would do it. I was thinking about including some common ones (int, str, email…) but I far as I can see it seems very flexible solution.
