### ISSUE TITLE
Text input - special characters áäüöæø and similar - result in overwritten characters.

### ISSUE THREAD

**Issue by Archina** [console-rs/dialoguer#116]
Entering input that contains special characters, like áäüöæø on an international keyboard leads to overwriting characters in the read.

This happens because the text cursor is only partly moved forward, as these special characters contain multiple bytes to encode themself.

I will be posting a proposed fix but I am not sure if this one will be universally correct. (Different OS may be handling the input differently?)

**Comment by Jakubzik** [comment]
Having the same problem (German Umlaute get swallowed on display, Arch, rustc 1.59, dialoguer 0.10.0)

**Comment by Gordon01** [comment]
I can't reproduce this on the latest master 
![image](https://github.com/console-rs/dialoguer/assets/4996834/341fd01f-f067-4b51-b2e3-0d36e41470f3)

@pksunkara perhaps it's fixed?
