### ISSUE TITLE
Typing any uppercase characters in an `Input` `interact_text` causes an error.

### ISSUE THREAD

**Issue by neelkarma** [console-rs/dialoguer#128]
When typing an uppercase character in an `Input`, it errors out. Doesn't matter whether <kbd>Shift</kbd> or <kbd>Caps. Lock</kbd> are used, both of them cause an error. Lowercase characters work fine. `Password` and `Confirm` are unaffected.

- OS: Windows 10
- Terminal: Windows Terminal Preview 1.10.1933.0
- Shell: Powershell Core 7.1.4

Code to reproduce (when the prompt appears, type any uppercase character):
```rs
use dialoguer::Input;

fn main() {
    let input: String = Input::new()
        .with_prompt("Test Prompt")
        .interact_text()
        .unwrap();
    println!("Input: {}", input);
}
```
Output:
```
Test Prompt: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotConnected, error: "Not a terminal" }', src\main.rs:7:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\dialoguer-input-bug.exe` (exit code: 101)
```

**Comment by neelkarma** [comment]
Also for some reason using `.interact()` instead of `.interact_text()` fixes the problem.

**Comment by spenserblack** [comment]
Thanks for point out that `.interact()` doesn't return an error!

I just found that `.interact()` does *not* help, though, when used with `.with_initial_text`.

I think that these lines are related


### Example

```rust
use dialoguer::Input;

fn main() {
    let _: String = Input::new() // Shift will not break this one
        .with_prompt("Test 1")
        .interact()
        .unwrap();
    let _: String = Input::new() // Shift will break this one
        .with_prompt("Test 2")
        .with_initial_text("Don't press shift!")
        .interact()
        .unwrap();
}
```

**Comment by pksunkara** [comment]
Can you please try checking the original comment issue too?

**Comment by spenserblack** [comment]
Using
```toml
dialoguer = "0.9"
```
it looks like the code in the original comment works, too. But I can't guarantee that there isn't some difference in my environment and @neelkarma's (the original commenter) that makes it work for me but not for them.

**Comment by spenserblack** [comment]
Nevermind, I didn't realize at first that the original comment was also reporting an issue with <kbd>Caps Lock</kbd>. <kbd>Shift</kbd> seems to work, but <kbd>Caps Lock</kbd> seems to continue to cause errors.

**Comment by connor4312** [comment]
I suspect this was fixed in https://github.com/console-rs/dialoguer/pull/192

**Comment by neelkarma** [comment]
Can confirm, the issue has been fixed. Sorry for the radio silence!
