### ISSUE TITLE
`Confirm::_interact_on` infinite loop when not a tty

### ISSUE THREAD

**Issue by ahcodedthat** [console-rs/dialoguer#148]
[`Confirm::_interact_on` calls `Term::read_key` in a loop](https://github.com/mitsuhiko/dialoguer/blob/f9c067bfe711d5a52cb6bac0c128d046d3ade594/src/prompts/confirm.rs#L185) but doesn't break out of the loop if the return value is `Key::Unknown`, which `read_key` returns if not connected to a terminal. This causes an infinite loop.

**Comment by physics515** [comment]
Is this why using the debugger in VS code causes an infinite loop of displaying the prompt?

**Comment by DanteMarshal** [comment]
This also happens when I launch something in an external terminal from VS Code (i.e. `"console": "externalTerminal"` in `launch.json`)
What could be the cause ?
