### ISSUE TITLE
Fuzzy Select: Special characters lead to panic

### ISSUE THREAD

**Issue by deg0nz** [console-rs/dialoguer#181]
Entering special characters that consist of more than one char (like ä, ö, ü, é, ê, ...) lead to a panic.

This seems to be due to the fact that we use a range in `search_term[0..cursor_pos]`.

I will check, if [using `Slice`s fixes the issue](https://doc.rust-lang.org/std/primitive.str.html#method.split_at).

![fuzzy-select-umlaut](https://user-images.githubusercontent.com/6370295/156933937-ecb201d8-272a-4f95-8136-7455e1bd607f.gif)

Edit: also found this while implementing #179

**Comment by deg0nz** [comment]
I digged into this and it seems to be an inherent property of unicode characters. Characters like `ä` actually are grapheme clusters and have a length of 3 chars. We need to consider that fact when splitting `str`.

The Rust standard library explicitly says, [that it does not solve the iteration over grapheme clusters.](https://doc.rust-lang.org/std/primitive.str.html#method.chars)

Since `fuzzy-select` is behind a feature, I suggest we also include  https://crates.io/crates/unicode-segmentation for the fuzzy select feature and split the search term with that crate to support non-ascii characters.

**Comment by Araxeus** [comment]
This is especially annoying for users that aren't English speakers

For example:
 Cyrillic. Hebrew. Chinese, Arabic, etc...
