### ISSUE TITLE
Optional input API

### ISSUE THREAD

**Issue by joepio** [console-rs/dialoguer#186]
Hi there! Thanks for creating this :)

I have some input fields that are optional. I'd like to have an API similar to this:

```rust
let number: Option<u32> = Input::new().with_prompt("What's your age?").interact()?;
```

Maybe I'm missing something in the docs, but I don't really see how I should achieve these optional inputs. 

I know you can use `.allow_empty`, but that doesn't really work for things like numbers.

**Comment by joepio** [comment]
Back here 2yrs later, trying again to switch from promptly to dialoguer.

Anyways, I still want to have a "skippable" form field, but I don't know how I can achieve this.

```rust
fn prompt_opt(msg: &str) -> AtomicResult<Option<String>> {
    dialoguer::Input::new()
        .with_prompt(msg)
        .interact()
        .map(|s: String| if s.is_empty() { None } else { Some(s) })
        .map_err(|e| format!("Error while prompting: {}", e).into())
}
```

This seemed sensible, but if I press enter when the string is empty nothing happens. I'm assuming I'm missing something obvious!

**Comment by jonassmedegaard** [comment]
I guess you are missing `.allow_empty(true)`.

**Comment by pksunkara** [comment]
Try `interact_with_opt` instead of `interact`

**Comment by jonassmedegaard** [comment]
Here's my patch: https://salsa.debian.org/debian/atomic-data-rust/-/blob/debian/latest/debian/patches/1001_promptly.patch?ref_type=heads

**Comment by jonassmedegaard** [comment]
> Try `interact_opt` instead of `interact`

Ah, right - that too.

**Comment by pksunkara** [comment]
Closing this until further response that the suggestion doesn't work.
