### ISSUE TITLE
Use of moved value `confirm`

### ISSUE THREAD

**Issue by ShayBox** [console-rs/dialoguer#262]
Since the last cargo release, changes in the git repo have made `with_prompt` take ownership of confirm, preventing re-use and requiring constant re-initialization.

**Comment by pksunkara** [comment]
Yes, it will be a breaking change to support the builder pattern.

> preventing re-use and requiring constant re-initialization.

You wouldn't need it. Can you describe more on the differences? How did it used to be and how did you need to change it?

**Comment by ShayBox** [comment]
I used it like this: `let mut confirm = Confirm::new();` which let you initialize Confirm, Input, etc once and set the theme once instead of doing it 50 times. The builder pattern is nice but the prompt_with method shouldn't be part of the builder, but on the variable the builder returns so it can be re-used as many times as needed.

**Comment by pksunkara** [comment]
Just to make sure I don't misunderstand, I would prefer a more concrete example with code. Please understand that I don't have the full context here compared to you.

**Comment by ShayBox** [comment]
```rust
let theme = ColorfulTheme::default();
        
        // Stable
        let mut confirm = Confirm::with_theme(&theme);
        if confirm.with_prompt("Question 1").interact().unwrap() {}
        if confirm.with_prompt("Question 2").interact().unwrap() {}
        if confirm.with_prompt("Question 3").interact().unwrap() {}

        // Git
        if Confirm::with_theme(&theme)
            .with_prompt("Question 1")
            .interact()
            .unwrap()
        {}
        if Confirm::with_theme(&theme)
            .with_prompt("Question 2")
            .interact()
            .unwrap()
        {}
        if Confirm::with_theme(&theme)
            .with_prompt("Question 3")
            .interact()
            .unwrap()
        {}
```
The git syntax is more verbose and repetitive

**Comment by pksunkara** [comment]
All the prompts are now cloneable so that you can reduce the code's duplicity.
